import tensorflow as tf

MODEL_NAME="models.densegan"

NUM_CLASSES = 3
CLASS_NAMES = ["circle", "rectangle", "triangle"]
LATENT_DIM = 100
IMG_SIZE = 28
IMG_DIM = IMG_SIZE * IMG_SIZE
LEARNING_RATE = 0.002
EPOCHS = 100
BATCH_SIZE = 64
SMOOTH = 0.1

IMG_SEED = 123456789
IMG_DIR = "data/training"

LOG_PATH = "data/logs"

SHAPE_RECTANGLE_NAME = "rectangle"
SHAPE_RECTANGLE_AMOUNT = 500
SHAPE_RECTANGLE_MIN_SIZE = 5
SHAPE_RECTANGLE_MAX_SIZE = 16

SHAPE_TRIANGLE_NAME = "triangle"
SHAPE_TRIANGLE_AMOUNT = 500
SHAPE_TRIANGLE_MIN_SIZE = 5
SHAPE_TRIANGLE_MAX_SIZE = 16

SHAPE_CIRCLE_NAME = "circle"
SHAPE_CIRCLE_AMOUNT = 500
SHAPE_CIRCLE_MIN_SIZE = 5
SHAPE_CIRCLE_MAX_SIZE = 10

