NUM_CLASSES = 3
LATENT_DIM = 100
IMG_SIZE = 28
IMG_DIM = IMG_SIZE * IMG_SIZE
LEARNING_RATE = 0.002
EPOCHS = 100
BATCH_SIZE = 64
SMOOTH = 0.1

IMG_SEED = 123456789
IMG_DIR = "data/training"


import tensorflow as tf
import os

BUFFER_SIZE = 60000
NUM_EXAMPLES_PER_CLASSES = 3
NUM_EXAMPLES = NUM_CLASSES * NUM_EXAMPLES_PER_CLASSES

# You will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF)
LOG_SEED = tf.random.normal([NUM_EXAMPLES, LATENT_DIM])

LOG_ROOT_DIR = './logs'
LOG_IMG_DIR = os.path.join(LOG_ROOT_DIR, "img")
CHECKPOINT_DIR = os.path.join(LOG_ROOT_DIR, 'checkpoints')
CHECKPOINT_PREFIX = os.path.join(CHECKPOINT_DIR, "ckpt")


SHAPE_RECTANGLE_NAME = "rectangle"
SHAPE_RECTANGLE_AMOUNT = 500
SHAPE_RECTANGLE_MIN_SIZE = 5
SHAPE_RECTANGLE_MAX_SIZE = 16

SHAPE_TRIANGLE_NAME = "triangle"
SHAPE_TRIANGLE_AMOUNT = 500
SHAPE_TRIANGLE_MIN_SIZE = 5
SHAPE_TRIANGLE_MAX_SIZE = 16

SHAPE_CIRCLE_NAME = "circle"
SHAPE_CIRCLE_AMOUNT = 500
SHAPE_CIRCLE_MIN_SIZE = 5
SHAPE_CIRCLE_MAX_SIZE = 10

